main.lua
web_chat.lua

Added WebChat hooking (Hook fires when message is sent from WebChat) 
and incremented plugin version so that plugins utilizing this API can check if Core supports it.

Added OnChat hook to the webchat

---

difficulties.lua

Lets wait with merging this until someone can test if it works.

Reverts workaround from https://github.com/mc-server/Core/pull/123

---

Info.lua
give.lua
tps.lua
weather.lua

Adds wrappers for the console commands give, unsafegive, tps, toggledownfall, and weather to account for recent changes to mcserver.

Fixes #124

---

console.lua
web_plugins.lua

This presents a much better view of plugins on both console and webadmin.
Note that this change requires mc-server/MCServer#1875 in order to work.

Updated plugin handling.

---

web_permissions.lua
web_ranks.lua

Adds a webadmin-based editor for Restrictions parallel to the Permissions.
Requires mc-server/MCServer#1897
Implements mc-server/MCServer#1331

Added group restrictions to the webadmin editor.

---

main.lua
web_chat.lua

Added a message in the webadmin when the core is loaded

Fixed possible security issue where HTML tags weren't removed

---

functions.lua
motd.lua

When using @@ you get a single @

You can now use @ properly in the motd

---

functions.lua

Removed BackCoords variable

---

main.lua

Fix global accedentally removed in 458e5d4

---

Info.lua
README.md
banlist.lua
console.lua
difficulties.lua
do.lua
enchant.lua
give.lua
gm.lua
kick.lua
me.lua
portal-worlds.lua
ranks.lua
regen.lua
teleport.lua
tell.lua
time.lua
viewdistance.lua
weather.lua
whitelist.lua

Command syntax:
- < angle brackets > = required argument
- [square brackets] = optional argument
- Multiple options separated with |
- … = argument can contain spaces
- (http://minecraft.gamepedia.com/Commands)
Command description:
- All sentences end with a period.
- Rewrote a few sentences for better consistency.
- New README generated with InfoDump.lua, removed old permissions now located in Essentials.
All commands have been tested after this change.

Fixed visual inconsistencies

---

motd.lua

Changed mc server to cuberite.

Updated motd.lua

---

banlist.lua
functions.lua
ondeath.lua
onkilling.lua

Removed the remnants of the old INI file, now using the banlist API.
Fixes #159.

Fixed banning for death in hardcore mode.

---

functions.lua
teleport.lua

- Removed unused TeleportRequests
- Players can now teleport to players located in other worlds (fixes #156)

Teleportation fixes

---

worldlimiter.lua

Closes https://github.com/cuberite/cuberite/issues/3134

Fixed WorldLimiter jitter

---

web_manageserver.lua

Comparison: http://i.imgur.com/9bP6CuK.png

Fixed html issue

---

Info.lua
README.md
seed.lua

Added command seed for in-game and console.

Added seed command

---

main.lua

This PR removes old code for hardcore mode which is not needed anymore.

Removed unused code

---

Info.lua
README.md
effect.lua

This PR adds the vanilla /effect command to Core.

Added /effect command

---

give.lua

I've added some technical blocks that were introduced in Minecraft 1.9 and 1.10 to the blacklist.

Added new blocks to blacklist

---

circle.yml

This fixes luarocks/luarocks#653 by first installing `luasec` and then `luasocket`

Fix luasec in CI

---

Info.lua

This PR adds aliases that exist in Bukkit and other servers.

Added aliases for /help and /plugins

---

difficulties.lua

Fix for the issue cuberite/cuberite#3622 .
This is the first time that I am working on a open source project and I just began reading into your codebase so any comment or help is appreciated.

Remove monsters when switching to peaceful

---

give.lua

Fixes the warnings since cuberite/cuberite#3882 was merged.

Use cItem.m_LoreTable in give command

---

Info.lua
README.md
difficulties.lua
summon.lua

Basic Summon Command

---

CONTRIBUTORS
LICENSE
spawn.lua

Spiritual replacement for #172, which is broken due to merge conflicts.
Not tested, requires thorough checking, although it is really only minor modifications of existing code.
Also added CONTRIBUTORS file and updated license to standard form.

Remove IniFile from spawn command

---

summon.lua

Also fixed an issue where "~" alone wouldn't return the relative coordinate.

Replace deprecated parameters

---

web_serversettings.lua

Fixes https://github.com/cuberite/cuberite/issues/4327

Make Webadmin port changes work

---

summon.lua

Revert "Add Zombie Villager to summon command"

---

web_serversettings.lua

This is a leftover from years ago. No longer works.

Remove IPv6 port setting

---

summon.lua

Reverts cuberite/Core#220
Depends on https://github.com/cuberite/cuberite/pull/4180

Add Zombie Villager to summon command

---

time.lua

Fix time command. Animations can no longer fight against themselves

---

banlist.lua
main.lua
web_plugins.lua
whitelist.lua

Update connected to cuberite/cuberite#5227

Remove "core" from console LOG macros

---

cmd_listgroups.lua
cmd_listranks.lua

Remove color codes from /listgroups and /listranks commands

---

CONTRIBUTORS
cmd_spawnpoint.lua

Updation SetBedPos in plugin to match changes in cuberite/cuberite#5300 look there for additional information (recomend to merge there two simultanously)

Updated /spawnpoint Command
